[package]
name = "calculator-gui"
version = "0.1.0"
edition = "2018"

[dependencies]
calculator = { path = "../calculator" }
eframe = "0.15.0"
serde = { version = "1", features = ["derive"], optional = true }
