// TODO: https://lalrpop.github.io/lalrpop/index.html

pub fn calculate(expr: &str) -> Result<f64, String> {
    Ok(0.0)
}

// This is autogenerated
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
